# Generated by Django 2.2.2 on 2019-07-01 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import frami.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('prescriber', models.ForeignKey(default=1, on_delete=models.SET(frami.api.models.get_deleted_user), related_name='prescribed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
