# Generated by Django 2.2.2 on 2019-07-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import frami.api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('unread', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Question')),
                ('user', models.ForeignKey(on_delete=models.SET(frami.api.models.get_deleted_user), related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
