# Generated by Django 2.2.2 on 2019-07-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='prescriber',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='user',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='creator',
        ),
    ]
