# Generated by Django 2.2.2 on 2019-07-18 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import frami.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_prescription_refill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=models.SET(frami.api.models.get_deleted_user), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=models.SET(frami.api.models.get_deleted_user), related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=models.SET(frami.api.models.get_deleted_user), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
